#!/bin/bash

ls | grep -v "debian" | xargs rm -r
rm -rf .pc

unset BRANCH
if [ -f debian/target ]; then
    source debian/target
    echo "target: $target"
fi


snapdir=$(mktemp -d)
echo "$snapdir"
pushd "$snapdir"
    git clone git@github.com:lxde/pcmanfm-qt snapshot
    pushd snapshot
       [  ! -z ${target+x} ] &&  git reset --hard "$target"
       description=$(git describe --tags)
       rm -rf .git*
    popd
    tar cfvJ snapshot.orig.tar.xz snapshot
popd
tar xf "$snapdir/snapshot.orig.tar.xz" --strip-components 1
dch "New snapshot: $description"
rm -rfv "$snapdir"
